"""add remediation to findings

Revision ID: 3073274850c8
Revises: 771e2f94ca80
Create Date: 2026-07-13 20:51:58.314414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3073274850c8"
down_revision: str | Sequence[str] | None = "771e2f94ca80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("findings", sa.Column("remediation", sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("findings", "remediation")
    # ### end Alembic commands ###
